name: Block Merge if Open Issues Exist

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-open-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open issues
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            if (issues.data.length > 0) {
              core.setFailed(`There are ${issues.data.length} open issues. Please resolve all issues before merging.`);
            }
